USE intrusions
GO
CREATE TABLE [intrusion-data]
(
	id INT,
	duration BIGINT,
	protocol_type VARCHAR(40),
	i_service VARCHAR(40),
	flag VARCHAR(40),
	src_bytes BIGINT,
	dst_bytes BIGINT,
	land BIGINT,
	wrong_fragment BIGINT,
	urgent BIGINT,
	hot BIGINT,
	num_failed_logins BIGINT,
	logged_in BIGINT,
	num_compromised BIGINT,
	root_shell BIGINT,
	su_attempted BIGINT,
	num_root BIGINT,
	num_file_creations BIGINT,
	num_shells BIGINT,
	num_access_files BIGINT,
	num_outbound_cmds BIGINT,
	is_host_login BIGINT,
	is_guest_login BIGINT,
	i_count BIGINT,
	srv_count BIGINT,
	serror_rate DECIMAL(3,2),
	srv_serror_rate DECIMAL(3,2),
	rerror_rate DECIMAL(3,2),
	srv_rerror_rate DECIMAL(3,2),
	same_srv_rate DECIMAL(3,2),
	diff_srv_rate DECIMAL(3,2),
	srv_diff_host_rate DECIMAL(3,2),
	dst_host_count BIGINT,
	dst_host_srv_count BIGINT,
	dst_host_same_srv_rate DECIMAL(3,2),
	dst_host_diff_srv_rate DECIMAL(3,2),
	dst_host_same_src_port_rate DECIMAL(3,2),
	dst_host_srv_diff_host_rate DECIMAL(3,2),
	dst_host_serror_rate DECIMAL(3,2),
	dst_host_srv_serror_rate DECIMAL(3,2),
	dst_host_rerror_rate DECIMAL(3,2),
	dst_host_srv_rerror_rate DECIMAL(3,2),
	status VARCHAR(40),
	status_type VARCHAR(40),
	parent_status_type VARCHAR(40)
)
GO
